### ISSUE TITLE
Unresolved identifier objc_synchronized

### ISSUE THREAD

**Issue by beloglazov** [ide/Synchronized#1]
Hi James,

After adding your pod to my project, I get the following build error:

```
.../Pods/Synchronized/Synchronized/Synchronized.swift:25:5: error: use of unresolved identifier 'objc_synchronized'
    objc_synchronized(object) {
    ^
.../Pods/Synchronized/Synchronized/Synchronized.swift:32:5: error: use of unresolved identifier 'objc_synchronized'
    objc_synchronized(object, closure)
    ^
```

Do you know what could be wrong?

Thanks,
Anton

**Comment by ide** [comment]
You might need to upgrade your CocoaPods to 0.36-pre: http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/. Older versions do not support Swift. Also using a Swift pod means you have to target iOS 8.0+, just a warning.

**Comment by beloglazov** [comment]
I see, thanks! I'll try it when it's released :)
