### ISSUE TITLE
Tag carthage-compatible commit with version number

### ISSUE THREAD

**Issue by cortices** [ide/Synchronized#4]
Currently it is necessary to use "master" to get the master branch from carthage. If the recent merged Carthage compatible commit was tagged with a semantic version (e.g. "2.0.0" or "v2.0") then the carthage version syntax could be used, which ensures version compatibility. (e.g. `github "ide/Synchronized" ~> 2.0.0`)

**Comment by ide** [comment]
Published https://github.com/ide/Synchronized/releases/tag/2.0.1.
